channels:
  - conda-forge
dependencies:
  - python==3.9
  - proj==9.0.1
  - pip==22.1.2
  - pip:
    - streamlit==1.10.0
    - matplotlib==3.5.2
    - numpy==1.23
    - pandas==1.4.3
    - notion_client==1.0.0
    - geopandas==0.11.0
    - cartopy==0.20.3
